name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - "9.6"
        cabal:
          - "3.10"
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: update cabal database
        run: cabal update
      - name: build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: run tests
        run: cabal test all
