name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - 9.0
          - 8.10
          - 8.8
        cabal:
          - 3.4
          - 3.2
          - 3.0
    steps:
      - uses: actions/checkout@v2
      - name: setup GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: update cabal database
        run: cabal update
      - name: build
        run: cabal build --enable-tests --enable-benchmarks all
      - name: run tests
        run: cabal test all
